<a href="https://colab.research.google.com/github/ArifaJannat2497/Python_Google_Colab/blob/Customer-Churn-analysis/Customer_Churn_Analysis_(PDSML_Day_6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Customer Churn Analysis

# PDSML Day-2 👉 Importing Libraries and Dataset

## Importing the essential libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import shap

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Customer-Churn.csv')

# PDSML Day-3 👉 Data Preprocessing (Part-1)

### Checking the head of the dataset

In [ ]:
dataset.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Checking the shape of the dataset

In [ ]:
dataset.shape

(7043, 21)

In [ ]:
dataset.head(), dataset.shape

(   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
 0  7590-VHVEG  Female              0     Yes         No       1           No
 1  5575-GNVDE    Male              0      No         No      34          Yes
 2  3668-QPYBK    Male              0      No         No       2          Yes
 3  7795-CFOCW    Male              0      No         No      45           No
 4  9237-HQITU  Female              0      No         No       2          Yes

       MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
 0  No phone service             DSL             No  ...               No
 1                No             DSL            Yes  ...              Yes
 2                No             DSL            Yes  ...               No
 3  No phone service             DSL            Yes  ...              Yes
 4                No     Fiber optic             No  ...               No

   TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
 0          No          No              No  Month-to-month              Yes
 1          No          No              No        One year               No
 2          No          No              No  Month-to-month              Yes
 3         Yes          No              No        One year               No
 4          No          No              No  Month-to-month              Yes

                PaymentMethod MonthlyCharges  TotalCharges Churn
 0           Electronic check          29.85         29.85    No
 1               Mailed check          56.95        1889.5    No
 2               Mailed check          53.85        108.15   Yes
 3  Bank transfer (automatic)          42.30       1840.75    No
 4           Electronic check          70.70        151.65   Yes

 [5 rows x 21 columns],
 (7043, 21))

### Checking how imbalanced your dataset is

In [ ]:
dataset['Churn'].value_counts(normalize=True)

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

### Data cleaning

#### Detecting the erroneous numeric columns by calculating the mean

In [ ]:
print(dataset['tenure'].mean())

32.37114865824223

In [ ]:
print(dataset['MonthlyCharges'].mean())

64.76169246059918

#### Converting the string entries to numeric and nan

In [ ]:
# print(dataset['TotalCharges'].mean())

In [ ]:
dataset['TotalCharges'].iloc[3331]

' '

#### Detecting the nan entries using iloc

In [ ]:
dataset['TotalCharges'] = pd.to_numeric(dataset['TotalCharges'], errors='coerce')

In [ ]:
print(dataset['TotalCharges'].iloc[3331])

nan

#### Dropping the nan-containing rows from the dataframe

In [ ]:
dataset.shape

(7043, 21)

In [ ]:
dataset = dataset.dropna(subset=['TotalCharges']).copy()

In [ ]:
dataset.shape

(7032, 21)

# PDSML Day-4 👉 Data Preprocessing (Part-2)

### Removing unnecessary features

In [ ]:
dataset.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
list(dataset.columns)

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [ ]:
X = dataset.drop(columns=['customerID', 'Churn'])
# ['Item1', 'Item2', ......] ----->Means a list

In [ ]:
list(X.columns)

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges']

In [ ]:
print(X.head())

   gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No
1    Male              0      No         No      34          Yes
2    Male              0      No         No       2          Yes
3    Male              0      No         No      45           No
4  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes
1                No             DSL            Yes           No
2                No             DSL            Yes          Yes
3  No phone service             DSL            Yes           No
4                No     Fiber optic             No           No

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month
1              Yes          No          No              No        One year
2               No          No          No              No  Month-to-month
3              Yes         Yes          No              No        One year
4               No          No          No              No  Month-to-month

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges
0              Yes           Electronic check           29.85         29.85
1               No               Mailed check           56.95       1889.50
2              Yes               Mailed check           53.85        108.15
3               No  Bank transfer (automatic)           42.30       1840.75
4              Yes           Electronic check           70.70        151.65

In [ ]:
X.shape

(7032, 19)

### Dependent variable declaration

In [ ]:
print(dataset['Churn'].head())

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [ ]:
y = dataset['Churn']

In [ ]:
y.map({'No': 0, 'Yes': 1,}) # {} ----> Means Dictionary Data Structure

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7032, dtype: int64

In [ ]:
y = y.map({'No': 0, 'Yes': 1,})

In [ ]:
print(y)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7032, dtype: int64

### Splitting the dataset into the training set and the test set

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify = y)

In [ ]:
print(X_train.head())

      gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
1413    Male              0     Yes        Yes      65          Yes
7003    Male              0      No         No      26           No
3355  Female              0     Yes         No      68          Yes
4494    Male              0      No         No       3          Yes
3541  Female              0     Yes         No      49           No

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
1413               Yes     Fiber optic            Yes          Yes
7003  No phone service             DSL             No           No
3355               Yes     Fiber optic             No          Yes
4494                No     Fiber optic             No          Yes
3541  No phone service             DSL            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1413              Yes         Yes          No              No        Two year
7003              Yes         Yes          No              No  Month-to-month
3355              Yes         Yes          No              No        Two year
4494               No          No          No             Yes  Month-to-month
3541               No          No         Yes              No  Month-to-month

     PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges
1413               No    Credit card (automatic)           94.55       6078.75
7003               No           Electronic check           35.75       1022.50
3355               No    Credit card (automatic)           90.20       6297.65
4494               No           Electronic check           84.30        235.05
3541               No  Bank transfer (automatic)           40.65       2070.75

In [ ]:
y.value_counts(normalize = True)

Churn
0    0.734215
1    0.265785
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize = True)

Churn
0    0.734186
1    0.265814
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize = True)

Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

# PDSML Day-5 👉 Data Preprocessing (Part-3)

### One-hot encoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#### Selecting the numeric columns

In [ ]:
num_cols = X.select_dtypes(include = np.number).columns.tolist()

In [ ]:
print(num_cols)

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

#### Selecting the categorical columns

In [ ]:
cat_cols = X.select_dtypes(exclude = np.number).columns.tolist()

In [ ]:
print(cat_cols)

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

#### Column transformations

In [ ]:
# pre-processing
pre = ColumnTransformer(
    transformers = [
        ("cat", OneHotEncoder(handle_unknown='ignore', sparse_output= False), cat_cols),
        ("num", 'passthrough', num_cols)

    ]
)

In [ ]:
print(pre.fit_transform(X))

[[1.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.9850e+01 2.9850e+01]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 3.4000e+01 5.6950e+01 1.8895e+03]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 2.0000e+00 5.3850e+01 1.0815e+02]
 ...
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 1.1000e+01 2.9600e+01 3.4645e+02]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 4.0000e+00 7.4400e+01 3.0660e+02]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 6.6000e+01 1.0565e+02 6.8445e+03]]

In [ ]:
# updated X
# X = pre.fit_transform(X)

In [ ]:
# print(X)

# PDSML Day-6 👉 Data Preprocessing (Part-4)

### Getting names of encoded categorical columns

In [ ]:
#cat_independent_variavles_names (cat_iv_names)
cat_iv_names = pre.named_transformers_['cat'].get_feature_names_out(cat_cols)

In [ ]:
print(cat_iv_names)

['gender_Female' 'gender_Male' 'Partner_No' 'Partner_Yes' 'Dependents_No'
 'Dependents_Yes' 'PhoneService_No' 'PhoneService_Yes' 'MultipleLines_No'
 'MultipleLines_No phone service' 'MultipleLines_Yes'
 'InternetService_DSL' 'InternetService_Fiber optic' 'InternetService_No'
 'OnlineSecurity_No' 'OnlineSecurity_No internet service'
 'OnlineSecurity_Yes' 'OnlineBackup_No' 'OnlineBackup_No internet service'
 'OnlineBackup_Yes' 'DeviceProtection_No'
 'DeviceProtection_No internet service' 'DeviceProtection_Yes'
 'TechSupport_No' 'TechSupport_No internet service' 'TechSupport_Yes'
 'StreamingTV_No' 'StreamingTV_No internet service' 'StreamingTV_Yes'
 'StreamingMovies_No' 'StreamingMovies_No internet service'
 'StreamingMovies_Yes' 'Contract_Month-to-month' 'Contract_One year'
 'Contract_Two year' 'PaperlessBilling_No' 'PaperlessBilling_Yes'
 'PaymentMethod_Bank transfer (automatic)'
 'PaymentMethod_Credit card (automatic)' 'PaymentMethod_Electronic check'
 'PaymentMethod_Mailed check']

### Combining the categorical columns with the numeric columns

In [ ]:
print(num_cols)

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [ ]:
all_iv_names = list(cat_iv_names) + num_cols

In [ ]:
print(all_iv_names)

['gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes', 'Dependents_No', 'Dependents_Yes', 'PhoneService_No', 'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes', 'PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check', 'SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

### Converting the transformed output to a DataFrame

In [ ]:
X_transformed = pre.fit_transform(X)

In [ ]:
print(X_transformed)

[[1.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.9850e+01 2.9850e+01]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 3.4000e+01 5.6950e+01 1.8895e+03]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 2.0000e+00 5.3850e+01 1.0815e+02]
 ...
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 1.1000e+01 2.9600e+01 3.4645e+02]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 4.0000e+00 7.4400e+01 3.0660e+02]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 6.6000e+01 1.0565e+02 6.8445e+03]]

In [ ]:
#transformed dataframe (tr_df)
tr_df = pd.DataFrame(X_transformed, columns = all_iv_names)
pd.set_option('display.max_columns', None)
print(tr_df.head())

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  \
0            1.0          0.0         0.0          1.0            1.0
1            0.0          1.0         1.0          0.0            1.0
2            0.0          1.0         1.0          0.0            1.0
3            0.0          1.0         1.0          0.0            1.0
4            1.0          0.0         1.0          0.0            1.0

   Dependents_Yes  PhoneService_No  PhoneService_Yes  MultipleLines_No  \
0             0.0              1.0               0.0               0.0
1             0.0              0.0               1.0               1.0
2             0.0              0.0               1.0               1.0
3             0.0              1.0               0.0               0.0
4             0.0              0.0               1.0               1.0

   MultipleLines_No phone service  MultipleLines_Yes  InternetService_DSL  \
0                             1.0                0.0                  1.0
1                             0.0                0.0                  1.0
2                             0.0                0.0                  1.0
3                             1.0                0.0                  1.0
4                             0.0                0.0                  0.0

   InternetService_Fiber optic  InternetService_No  OnlineSecurity_No  \
0                          0.0                 0.0                1.0
1                          0.0                 0.0                0.0
2                          0.0                 0.0                0.0
3                          0.0                 0.0                0.0
4                          1.0                 0.0                1.0

   OnlineSecurity_No internet service  OnlineSecurity_Yes  OnlineBackup_No  \
0                                 0.0                 0.0              0.0
1                                 0.0                 1.0              1.0
2                                 0.0                 1.0              0.0
3                                 0.0                 1.0              1.0
4                                 0.0                 0.0              1.0

   OnlineBackup_No internet service  OnlineBackup_Yes  DeviceProtection_No  \
0                               0.0               1.0                  1.0
1                               0.0               0.0                  0.0
2                               0.0               1.0                  1.0
3                               0.0               0.0                  0.0
4                               0.0               0.0                  1.0

   DeviceProtection_No internet service  DeviceProtection_Yes  TechSupport_No  \
0                                   0.0                   0.0             1.0
1                                   0.0                   1.0             1.0
2                                   0.0                   0.0             1.0
3                                   0.0                   1.0             0.0
4                                   0.0                   0.0             1.0

   TechSupport_No internet service  TechSupport_Yes  StreamingTV_No  \
0                              0.0              0.0             1.0
1                              0.0              0.0             1.0
2                              0.0              0.0             1.0
3                              0.0              1.0             1.0
4                              0.0              0.0             1.0

   StreamingTV_No internet service  StreamingTV_Yes  StreamingMovies_No  \
0                              0.0              0.0                 1.0
1                              0.0              0.0                 1.0
2                              0.0              0.0                 1.0
3                              0.0              0.0                 1.0
4                              0.0              0.0                 1.0

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                  0.0                  0.0
1                                  0.0                  0.0
2                                  0.0                  0.0
3                                  0.0                  0.0
4                                  0.0                  0.0

   Contract_Month-to-month  Contract_One year  Contract_Two year  \
0                      1.0                0.0                0.0
1                      0.0                1.0                0.0
2                      1.0                0.0                0.0
3                      0.0                1.0                0.0
4                      1.0                0.0                0.0

   PaperlessBilling_No  PaperlessBilling_Yes  \
0                  0.0                   1.0
1                  1.0                   0.0
2                  0.0                   1.0
3                  1.0                   0.0
4                  0.0                   1.0

   PaymentMethod_Bank transfer (automatic)  \
0                                      0.0
1                                      0.0
2                                      0.0
3                                      1.0
4                                      0.0

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                    0.0                             1.0
1                                    0.0                             0.0
2                                    0.0                             0.0
3                                    0.0                             0.0
4                                    0.0                             1.0

   PaymentMethod_Mailed check  SeniorCitizen  tenure  MonthlyCharges  \
0                         0.0            0.0     1.0           29.85
1                         1.0            0.0    34.0           56.95
2                         1.0            0.0     2.0           53.85
3                         0.0            0.0    45.0           42.30
4                         0.0            0.0     2.0           70.70

   TotalCharges
0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65

In [ ]:
print(tr_df)

      gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  \
0               1.0          0.0         0.0          1.0            1.0
1               0.0          1.0         1.0          0.0            1.0
2               0.0          1.0         1.0          0.0            1.0
3               0.0          1.0         1.0          0.0            1.0
4               1.0          0.0         1.0          0.0            1.0
...             ...          ...         ...          ...            ...
7027            0.0          1.0         0.0          1.0            0.0
7028            1.0          0.0         0.0          1.0            0.0
7029            1.0          0.0         0.0          1.0            0.0
7030            0.0          1.0         0.0          1.0            1.0
7031            0.0          1.0         1.0          0.0            1.0

      Dependents_Yes  PhoneService_No  PhoneService_Yes  MultipleLines_No  \
0                0.0              1.0               0.0               0.0
1                0.0              0.0               1.0               1.0
2                0.0              0.0               1.0               1.0
3                0.0              1.0               0.0               0.0
4                0.0              0.0               1.0               1.0
...              ...              ...               ...               ...
7027             1.0              0.0               1.0               0.0
7028             1.0              0.0               1.0               0.0
7029             1.0              1.0               0.0               0.0
7030             0.0              0.0               1.0               0.0
7031             0.0              0.0               1.0               1.0

      MultipleLines_No phone service  ...  PaperlessBilling_No  \
0                                1.0  ...                  0.0
1                                0.0  ...                  1.0
2                                0.0  ...                  0.0
3                                1.0  ...                  1.0
4                                0.0  ...                  0.0
...                              ...  ...                  ...
7027                             0.0  ...                  0.0
7028                             0.0  ...                  0.0
7029                             1.0  ...                  0.0
7030                             0.0  ...                  0.0
7031                             0.0  ...                  0.0

      PaperlessBilling_Yes  PaymentMethod_Bank transfer (automatic)  \
0                      1.0                                      0.0
1                      0.0                                      0.0
2                      1.0                                      0.0
3                      0.0                                      1.0
4                      1.0                                      0.0
...                    ...                                      ...
7027                   1.0                                      0.0
7028                   1.0                                      0.0
7029                   1.0                                      0.0
7030                   1.0                                      0.0
7031                   1.0                                      1.0

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                       0.0                             1.0
1                                       0.0                             0.0
2                                       0.0                             0.0
3                                       0.0                             0.0
4                                       0.0                             1.0
...                                     ...                             ...
7027                                    0.0                             0.0
7028                                    1.0                             0.0
7029                                    0.0                             1.0
7030                                    0.0                             0.0
7031                                    0.0                             0.0

      PaymentMethod_Mailed check  SeniorCitizen  tenure  MonthlyCharges  \
0                            0.0            0.0     1.0           29.85
1                            1.0            0.0    34.0           56.95
2                            1.0            0.0     2.0           53.85
3                            0.0            0.0    45.0           42.30
4                            0.0            0.0     2.0           70.70
...                          ...            ...     ...             ...
7027                         1.0            0.0    24.0           84.80
7028                         0.0            0.0    72.0          103.20
7029                         0.0            0.0    11.0           29.60
7030                         1.0            1.0     4.0           74.40
7031                         0.0            0.0    66.0          105.65

      TotalCharges
0            29.85
1          1889.50
2           108.15
3          1840.75
4           151.65
...            ...
7027       1990.50
7028       7362.90
7029        346.45
7030        306.60
7031       6844.50

[7032 rows x 45 columns]